[build-system]
requires = [
    "setuptools",
    "wheel",
    "nanobind",
    "conan",
    "chardet",
    "ninja",
]
build-backend = "setuptools.build_meta"

[project]
name = "sim_estab"
dynamic = [
    "version",
    "description",
    "readme",
    "requires-python",
    "dependencies",
    "optional-dependencies",
    "authors",
    "license",
    "urls",
]